name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
      GIGACHAT_TOKEN: ${{ secrets.GIGACHAT_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull and Restart Docker Compose
        run: |
          docker compose pull
          docker compose up -d --build